services:

  # ─── PostgreSQL ───────────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ─── Auth Service instances ───────────────────────────────────────
  auth-service-1:
    image: ghcr.io/grishagor28/auth-service:latest
    container_name: auth-service-1
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/auth_db
      - INSTANCE_NAME=auth-service-1
    networks:
      - backend
      - elk_default
    depends_on:
      postgres:
        condition: service_healthy

  auth-service-2:
    image: ghcr.io/grishagor28/auth-service:latest
    container_name: auth-service-2
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/auth_db
      - INSTANCE_NAME=auth-service-2
    networks:
      - backend
      - elk_default
    depends_on:
      postgres:
        condition: service_healthy

  # ─── Todo Service instances ───────────────────────────────────────
  todo-service-1:
    image: ghcr.io/grishagor28/todo-service:latest
    container_name: todo-service-1
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/todo_db
      - INSTANCE_NAME=todo-service-1
    networks:
      - backend
      - elk_default
    depends_on:
      postgres:
        condition: service_healthy

  todo-service-2:
    image: ghcr.io/grishagor28/todo-service:latest
    container_name: todo-service-2
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/todo_db
      - INSTANCE_NAME=todo-service-2
    networks:
      - backend
      - elk_default
    depends_on:
      postgres:
        condition: service_healthy

  # ─── Nginx Load Balancer ──────────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: load-balancer
    ports:
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./nginx/active-active.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - auth-service-1
      - auth-service-2
      - todo-service-1
      - todo-service-2

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
  elk_default:
    external: true
