events {}

http {

  # ─── Auth Service — active/passive ───────────────────────────────
  # auth-service-1 обрабатывает все запросы
  # auth-service-2 подключается только если auth-service-1 недоступен
  upstream auth_backend {
    server auth-service-1:8001;
    server auth-service-2:8001 backup;
  }

  # ─── Todo Service — active/passive ───────────────────────────────
  # todo-service-1 обрабатывает все запросы
  # todo-service-2 подключается только если todo-service-1 недоступен
  upstream todo_backend {
    server todo-service-1:8002;
    server todo-service-2:8002 backup;
  }

  server {
    listen 8001;

    location / {
      proxy_pass http://auth_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 8002;

    location / {
      proxy_pass http://todo_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}
