events {}

http {

  upstream auth_backend {
    server auth-service-1:8001;
    server auth-service-2:8001;
  }

  upstream todo_backend {
    server todo-service-1:8002;
    server todo-service-2:8002;
  }

  server {
    listen 8001;

    location / {
      proxy_pass http://auth_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 8002;

    location / {
      proxy_pass http://todo_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}
